apiVersion: v1
kind: Pod
metadata:
  name: alketas-debug
spec:
  containers:
    - name: alketas-debug
      image: olafradicke/alketas:0.10
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      # Just spin & wait forever
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      imagePullPolicy: IfNotPresent
      env:
        - name: VAULT_ADDR
          value: "https://openbao.openbao:8200"
        - name: VAULT_CACERT
          value: "/alketas/certs/root-ca.crt"
        - name: VAULT_SKIP_VERIFY
          value: "false"
        - name: VAULT_RENEW_TOKENS
          value: "/alketas/confs/tokens.yaml"
      volumeMounts:
        - name: renew-tokens
          mountPath: "/alketas/confs" # tokens.yaml
          readOnly: true
        - name: root-ca
          mountPath: "/alketas/certs" # root-ca.crt
          readOnly: true

  restartPolicy: OnFailure
  volumes:
    - name: renew-tokens
      secret:
        secretName: renew-tokens
        optional: true
    - name: root-ca
      secret:
        secretName: root-ca
        optional: true