apiVersion: v1
kind: Secret
metadata:
  name: renew-tokens
stringData:
  tokens.yaml: |
    tokens:
      - name: "group-01"
        token: "qwertyui"
      - name: "grpup-02"
        token: "asdfghjk"
      - name: "grpup-03"
        token: "zxcvbnm"
